export default {
	ADD_PARENT: 'ADD_PARENT',
	SELECT_ALL_GROUPS: 'SELECT_ALL_GROUPS',
	SET_NEW_USER: 'SET_NEW_USER',
	SET_CURRENT_DATA: 'SET_CURRENT_DATA',
	SET_GROUP: 'SET_GROUP',
	SET_TO_GROUP: 'SET_TO_GROUP'
};
